# Generated by Django 4.2.7 on 2023-11-09 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_accesstoken_delete_refreshtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
