version: "3.8"

services:
  db:
    image: postgres:16.0-alpine
    env_file: .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: dockers/api/Dockerfile.dev
    command: ["/tmp/entrypoint.sh"]
    env_file:
      - .env.dev
    volumes:
      - ./api:/app
    ports:
      - "8081:8000"
    depends_on:
      - db
    networks:
      - backend

  ui:
    build:
      context: .
      dockerfile: dockers/ui/Dockerfile.dev
    volumes:
      - ./ui:/app
      # We don't want to copy local machine node_modules into docker space
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api

networks:
  backend:
    driver: bridge

volumes:
  db_data:
