version: '3.8'

services:
  db:
    image: postgres:14  # Using version 14 as the latest version
    env_file: .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: dockers/api/Dockerfile.dev
    command: ["/tmp/wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - .env.dev  # Specify your .env.dev file here
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
