version: "3.8"

services:
  db:
    image: postgres:16.0-alpine
    env_file: .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "7878:5432"

  api:
    build:
      context: .
      dockerfile: dockers/api/Dockerfile.dev
    command: ["/tmp/entrypoint.sh"]
    env_file:
      - .env.dev
    volumes:
      - ./api:/app
    ports:
      - "8085:8000"
    depends_on:
      - db
    networks:
      - backend
    stdin_open: true  # Keep stdin open for interactive debugging
    tty: true         # Allocate a pseudo-TTY for interactive debugging

  ui:
    build:
      context: .
      dockerfile: dockers/ui/Dockerfile.dev
    volumes:
      - ./ui:/app
      # We don't want to copy local machine node_modules into docker space
      - /app/node_modules
    ports:
      - "5173:5432"
    depends_on:
      - api

  browserless:
    image: browserless/chrome:latest
    environment:
      - MAX_CONCURRENT_SESSIONS=10
    profiles: ["on_demand"]
    ports:
      - "3008:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
