# Dockerfile for Nginx
FROM nginx:alpine

# Remove default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx configuration
COPY dockers/api/nginx.aws.conf /etc/nginx/conf.d/
