# Use an official Python runtime as a base image
FROM python:3.11-bookworm

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY api /app/

# Install Poetry
RUN pip install poetry

# Install project dependencies
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

# Set environment variables for Django
ENV PYTHONUNBUFFERED 1

# Copy the wait-for-it script
COPY scripts/wait-for-it.sh /tmp/wait-for-it.sh
RUN chmod +x /tmp/wait-for-it.sh

# Copy the entrypoint script
COPY scripts/entrypoint.sh /tmp/entrypoint.sh
RUN chmod +x /tmp/entrypoint.sh


# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["gunicorn", "app.wsgi:application", "--bind", "0.0.0.0:8000"]
