- name: Check SSH connection
  hosts: prod
  gather_facts: no
  vars_files:
    - xxx.yml
  tasks:
  - name: Create SSH key file from vault variable
    copy:
      content: "sss"
      dest: "./ec2_ssh_key.pem"
      mode: '0600'
  - name: Creating an empty file
    file:
        path: "tom.txt"
        state: touch

#  - name: Ping test
#    ansible.builtin.ping:
  vars:
    ansible_ssh_private_key_file: "./ec2_ssh_key.pem"
    ansible_user: "{{ ec2user }}"
