- name: Check SSH connection
  hosts: lh
  gather_facts: no
  vars_files:
    - vault-stag.yml
  tasks:
    - name: Create SSH key file from vault variable
      copy:
        content: "{{ ec2_ssh_key }}"
        dest: "./ec2_ssh_key.pem"
        mode: '0600'

- name: Run SSH job
  hosts: stag
  gather_facts: no
  vars_files:
    - vault-stag.yml
  vars:
    ansible_ssh_private_key_file: "./ec2_ssh_key.pem"
    ansible_user: "{{ ec2user }}"
    repo_url: "git@github.com:crypturgus/dactyl.git"
    repo_dir: "/home/ec2-user/dactyl/"
  tasks:
    - name: Ping test
      ansible.builtin.ping:

#    - name: Fetch the repository
#      ansible.builtin.git:
#        repo: "{{ repo_url }}"
#        dest: "{{ repo_dir }}"
#        version: master
#        force: yes
#      become: yes # if needed

#    - name: Reset repository to latest master
#      ansible.builtin.command:
#        cmd: ssh -T git@github.com
#        chdir: "{{ repo_dir }}"
#      become: yes # if needed

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
        version: "test-deploy"
